---
- name: Instalar Docker en la Raspberry Pi
  hosts: raspberry
  become: true

  tasks:
    - name: Instalar dependencias previas
      apt:
        name:
          - ca-certificates
          - curl
        state: present
        update_cache: true

    - name: Crear directorio para la llave GPG de Docker
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: "0755"

    - name: Descargar la llave GPG oficial de Docker
      get_url:
        url: https://download.docker.com/linux/debian/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: "0644"

    - name: Agregar el repositorio de Docker
      apt_repository:
        repo: "deb [arch=arm64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
        state: present
        filename: docker

    - name: Instalar Docker Engine y plugins
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
        update_cache: true

    - name: Agregar el usuario luis al grupo docker
      user:
        name: luis
        groups: docker
        append: true

    - name: Asegurar que Docker inicie con el sistema
      service:
        name: docker
        state: started
        enabled: true
